// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWcIKAn3pGF4VkIkWlx4N3zwe0tUCek2w',
    appId: '1:673009725144:web:114bf3ab1b9c87f7b8f1ad',
    messagingSenderId: '673009725144',
    projectId: 'sharedata-dc6ba',
    authDomain: 'sharedata-dc6ba.firebaseapp.com',
    databaseURL: 'https://sharedata-dc6ba-default-rtdb.firebaseio.com',
    storageBucket: 'sharedata-dc6ba.appspot.com',
    measurementId: 'G-VLRRDEYFCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-QgYM3bNhctP0c4CiHtX5uOvG9t2i61s',
    appId: '1:673009725144:android:b090d2976849e363b8f1ad',
    messagingSenderId: '673009725144',
    projectId: 'sharedata-dc6ba',
    databaseURL: 'https://sharedata-dc6ba-default-rtdb.firebaseio.com',
    storageBucket: 'sharedata-dc6ba.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDflnExYjMf5j24qZWJQS0-WGDR2I15Jro',
    appId: '1:673009725144:ios:8a58659c5bd498a6b8f1ad',
    messagingSenderId: '673009725144',
    projectId: 'sharedata-dc6ba',
    databaseURL: 'https://sharedata-dc6ba-default-rtdb.firebaseio.com',
    storageBucket: 'sharedata-dc6ba.appspot.com',
    iosClientId: '673009725144-josqolpoceju1n47r15vg354rajffb03.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDflnExYjMf5j24qZWJQS0-WGDR2I15Jro',
    appId: '1:673009725144:ios:8a58659c5bd498a6b8f1ad',
    messagingSenderId: '673009725144',
    projectId: 'sharedata-dc6ba',
    databaseURL: 'https://sharedata-dc6ba-default-rtdb.firebaseio.com',
    storageBucket: 'sharedata-dc6ba.appspot.com',
    iosClientId: '673009725144-josqolpoceju1n47r15vg354rajffb03.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebase',
  );
}
